# Generated by Django 4.2 on 2024-08-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='Data de publicação')),
                ('titulo_blog', models.CharField(max_length=200)),
                ('conteudo_artigo', models.TextField()),
            ],
        ),
    ]
